apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-team-ns-quota
  namespace: dev-team
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"
    pods: "10"

# 2 CPU = 2000m/10  = 200m
# 2 Gi  = 2000Mi/10 = 200Mi