- name: Create user accounts with plain pw
  hosts: clients
  remote_user: root 
  vars_files:
    - secret.yaml

  tasks:
  - name: create user account on remote servers 
    user:
      name: haseduser2
      password: "{{ secret | password_hash('sha512') }}"
      shell: /bin/bash
      state: present