apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-log-reader-binding
  namespace: dev-team
subjects:
- kind: User # Authentication
  name: nextops.t24@gmail.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #Authorization
  name: pod-log-reader
  apiGroup: rbac.authorization.k8s.io