- name: creating hostname var using command
  hosts: clients #(client01, client02)
  remote_user: root 

  tasks:
  - name: creating hostname dyn var using command 
    command: hostname
    register: hostname_var # this is to register a dyn var during play book execution
  
  - name: print the value from the earlier var 
    debug:
      msg: "{{ hostname_var.stdout }}"
  
  - name: install tree pkd only one client02
    apt:
      name: tree
      state: present 
    when: hostname_var.stdout == "client02"