- name: Install LAMP stack
  hosts: clients 
  remote_user: root
  vars_files:                             # attribute to reference vars from a file
  - variables.txt 

  tasks:
  - name: Running apt update 
    apt:                              #module name
      update-cache: true              #attribute list
  
  - name: install apache2
    apt:                              #module name
      name: "{{ apache_pkg }}"        #attribute list
      state: present 
  
  - name: Start apache2 service 
    service:                          #module name
      name: "{{ apache_pkg }}"        #attibute list
      state: started
      enabled: yes

  - name: Install mysql community edition
    apt:
      name: "{{ mysql_pkg }}" 
      state: present 
  
  - name: Start mysql service 
    service:
      name: "{{ mysql_service }}"
      state: started 
      enabled: yes
  
  - name: Install PHP 
    apt:
      name: "{{ php_pkgs }}"
      state: present  
  
  handlers:
  - name: Restart apache2 service 
    service:                          #module name
      name: "{{ apache_pkg }}"        #attibute list
      state: restarted

  - name: Restart mysql service 
    service:
      name: "{{ mysql_service }}"
      state: restarted 