apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy
  labels:
    app: httpd
    type: deployment
spec: 
  replicas: 5
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      name: httpd
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  labels: 
    app: httpd
    type: service
spec:
  selector:
    app: httpd
  ports:
  - port: 80
    targetPort: 80
  type: NodePort