apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lb-deploy
  labels:
    app: nginx-lb
spec: 
  replicas: 4
  selector:
    matchLabels:
      app: nginx-lb
  template:
    metadata:
      name: nginx-lb
      labels:
        app: nginx-lb
    spec:
      containers:
        - name: nginx-lb
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-service
  labels:
    app: nginx-lb
spec:
  selector:
    app: nginx-lb 
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer  #Layer 4